[toolchain]
package_manager = "npm"

[features]
seeds = false
skip-lint = false

[programs.localnet]
fairfun_rewards = "HsydRBzU6Bcw6ku3h4K6JqimRTxTeCfvZQL6yDBvAi4A"

[programs.devnet]
fairfun_rewards = "HsydRBzU6Bcw6ku3h4K6JqimRTxTeCfvZQL6yDBvAi4A"

[programs.mainnet]
fairfun_rewards = "HsydRBzU6Bcw6ku3h4K6JqimRTxTeCfvZQL6yDBvAi4A"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/mainnet-deployer.json"
