[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
fairfun_rewards = "HsydRBzU6Bcw6ku3h4K6JqimRTxTeCfvZQL6yDBvAi4A"

[programs.localnet]
fairfun_rewards = "HsydRBzU6Bcw6ku3h4K6JqimRTxTeCfvZQL6yDBvAi4A"

[programs.mainnet]
fairfun_rewards = "6NPfR5MSEuhwhZsXm4FKF4V1ULSvTPDaubYGkKVpVsPS"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/77cQ99WQ2FWQT19kgpN2a9CfgYSfDqpomNVGtyYUrpAY.json"

[hooks]
