# Backend config for stardust-protocol
BUN_PORT = 3005

[solana]
rpc = "https://beta.helius-rpc.com/?api-key=093c9b83-eb11-418c-8aeb-b96bf06c848e"

[main_token]
mint = "So11111111111111111111111111111111111111112"

[price]
api = "https://api.coingecko.com/api/v3"

[authority]
# IMPORTANT: Replace with actual keypair for production
secret_key = ""

