import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import {
    Keypair,
    PublicKey,
    LAMPORTS_PER_SOL,
} from "@solana/web3.js";
import {
    getAssociatedTokenAddress,
    createAssociatedTokenAccountInstruction,
    getAccount,
    createMint,
    mintTo,
} from "@solana/spl-token";
import { expect } from "chai";

// Import the IDL type (generated by anchor build)
import { StarNft } from "../target/types/star_nft";

describe("star-nft", () => {
    const provider = anchor.AnchorProvider.env();
    anchor.setProvider(provider);

    const program = anchor.workspace.StarNft as Program<StarNft>;

    // Test authority
    const authority = Keypair.generate();

    // Test stardust mint (simulating the stardust token)
    let stardustMint: PublicKey;
    const stardustMintAuthority = Keypair.generate();

    // PDAs
    let statePda: PublicKey;
    let treasuryPda: PublicKey;

    // Test parameters
    const STARDUST_COST = new anchor.BN(1_000_000_000_000); // 1M with 6 decimals (1000 * 10^9)

    // Rarity probabilities (sums to 10000 = 100%)
    const RARITY_PROBABILITIES: number[] = [5000, 3000, 1500, 450, 50]; // Common to Legendary

    // Treasury percentages [min, max] in basis points
    // Common: 0.001% - 0.005% = 1-5bp
    // Legendary: 0.5% - 2% = 50-200bp
    const TREASURY_PERCENTAGES: number[][] = [
        [1, 5],      // Common
        [5, 20],     // Uncommon  
        [20, 100],   // Rare
        [100, 500],  // Epic
        [500, 2000], // Legendary
    ];

    before(async () => {
        // Derive PDAs
        [statePda] = PublicKey.findProgramAddressSync(
            [Buffer.from("star_nft_state")],
            program.programId
        );

        [treasuryPda] = PublicKey.findProgramAddressSync(
            [Buffer.from("treasury")],
            program.programId
        );

        // Create test stardust mint
        await provider.connection.requestAirdrop(
            stardustMintAuthority.publicKey,
            5 * LAMPORTS_PER_SOL
        );

        // Wait for airdrop confirmation
        await new Promise(resolve => setTimeout(resolve, 1000));

        stardustMint = await createMint(
            provider.connection,
            stardustMintAuthority,
            stardustMintAuthority.publicKey,
            null,
            9 // 9 decimals like the stardust token
        );

        console.log("Test Stardust Mint:", stardustMint.toBase58());
    });

    it("Initializes the STAR NFT program", async () => {
        await program.methods
            .initialize(
                STARDUST_COST,
                RARITY_PROBABILITIES,
                TREASURY_PERCENTAGES
            )
            .accounts({
                state: statePda,
                treasury: treasuryPda,
                stardustMint: stardustMint,
                authority: provider.wallet.publicKey,
                systemProgram: anchor.web3.SystemProgram.programId,
            })
            .rpc();

        // Verify state
        const state = await program.account.starNftState.fetch(statePda);
        expect(state.authority.toBase58()).to.equal(provider.wallet.publicKey.toBase58());
        expect(state.stardustMint.toBase58()).to.equal(stardustMint.toBase58());
        expect(state.stardustCost.toNumber()).to.equal(STARDUST_COST.toNumber());
        expect(state.totalNftsMinted.toNumber()).to.equal(0);

        console.log("STAR NFT Program initialized!");
        console.log("State PDA:", statePda.toBase58());
        console.log("Treasury PDA:", treasuryPda.toBase58());
    });

    it("Funds the treasury", async () => {
        const fundAmount = 10 * LAMPORTS_PER_SOL; // 10 SOL

        await program.methods
            .fundTreasury(new anchor.BN(fundAmount))
            .accounts({
                state: statePda,
                treasury: treasuryPda,
                funder: provider.wallet.publicKey,
                systemProgram: anchor.web3.SystemProgram.programId,
            })
            .rpc();

        const treasuryBalance = await provider.connection.getBalance(treasuryPda);
        expect(treasuryBalance).to.be.greaterThan(0);

        console.log("Treasury funded with", fundAmount / LAMPORTS_PER_SOL, "SOL");
        console.log("Treasury balance:", treasuryBalance / LAMPORTS_PER_SOL, "SOL");
    });

    it("Mints a STAR NFT by burning stardust", async () => {
        const user = provider.wallet;

        // Create user's stardust token account and mint tokens
        const userStardustAccount = await getAssociatedTokenAddress(
            stardustMint,
            user.publicKey
        );

        // Create ATA for user
        const ataIx = createAssociatedTokenAccountInstruction(
            user.publicKey,
            userStardustAccount,
            user.publicKey,
            stardustMint
        );

        const tx = new anchor.web3.Transaction().add(ataIx);
        await provider.sendAndConfirm(tx);

        // Mint stardust to user (simulating they earned stardust)
        await mintTo(
            provider.connection,
            stardustMintAuthority,
            stardustMint,
            userStardustAccount,
            stardustMintAuthority,
            STARDUST_COST.toNumber() * 5 // Give them enough for 5 mints
        );

        // Get user stardust balance before
        const balanceBefore = (await getAccount(provider.connection, userStardustAccount)).amount;
        console.log("User stardust before:", Number(balanceBefore) / 1e9);

        // Get current NFT count
        const stateBefore = await program.account.starNftState.fetch(statePda);
        const nftIndex = stateBefore.totalNftsMinted;

        // Derive NFT PDA
        const [starNftPda] = PublicKey.findProgramAddressSync(
            [
                Buffer.from("star_nft"),
                user.publicKey.toBuffer(),
                nftIndex.toArrayLike(Buffer, "le", 8),
            ],
            program.programId
        );

        // Mint STAR NFT
        await program.methods
            .mintStarNft()
            .accounts({
                state: statePda,
                starNft: starNftPda,
                stardustMint: stardustMint,
                userStardust: userStardustAccount,
                user: user.publicKey,
                tokenProgram: anchor.utils.token.TOKEN_PROGRAM_ID,
                systemProgram: anchor.web3.SystemProgram.programId,
            })
            .rpc();

        // Verify stardust was burned
        const balanceAfter = (await getAccount(provider.connection, userStardustAccount)).amount;
        expect(Number(balanceAfter)).to.equal(Number(balanceBefore) - STARDUST_COST.toNumber());
        console.log("User stardust after:", Number(balanceAfter) / 1e9);
        console.log("Stardust burned:", STARDUST_COST.toNumber() / 1e9);

        // Verify NFT was created
        const nft = await program.account.starNft.fetch(starNftPda);
        expect(nft.owner.toBase58()).to.equal(user.publicKey.toBase58());
        expect(nft.rarity).to.be.lessThanOrEqual(4); // 0-4 rarity
        expect(nft.treasuryClaimPct).to.be.greaterThan(0);

        const rarityNames = ["Common", "Uncommon", "Rare", "Epic", "Legendary"];
        console.log("NFT Minted!");
        console.log("  Rarity:", rarityNames[nft.rarity], `(${nft.rarity})`);
        console.log("  Treasury Claim:", nft.treasuryClaimPct / 100, "%");
        console.log("  NFT Index:", nft.nftIndex.toNumber());

        // Verify state updated
        const stateAfter = await program.account.starNftState.fetch(statePda);
        expect(stateAfter.totalNftsMinted.toNumber()).to.equal(nftIndex.toNumber() + 1);
    });

    it("Burns STAR NFT to claim treasury", async () => {
        const user = provider.wallet;

        // First mint a new NFT for testing burn
        const userStardustAccount = await getAssociatedTokenAddress(
            stardustMint,
            user.publicKey
        );

        const stateBefore = await program.account.starNftState.fetch(statePda);
        const nftIndex = stateBefore.totalNftsMinted;

        const [starNftPda] = PublicKey.findProgramAddressSync(
            [
                Buffer.from("star_nft"),
                user.publicKey.toBuffer(),
                nftIndex.toArrayLike(Buffer, "le", 8),
            ],
            program.programId
        );

        // Mint NFT
        await program.methods
            .mintStarNft()
            .accounts({
                state: statePda,
                starNft: starNftPda,
                stardustMint: stardustMint,
                userStardust: userStardustAccount,
                user: user.publicKey,
                tokenProgram: anchor.utils.token.TOKEN_PROGRAM_ID,
                systemProgram: anchor.web3.SystemProgram.programId,
            })
            .rpc();

        // Get NFT details
        const nft = await program.account.starNft.fetch(starNftPda);
        console.log("Minted NFT for burn test, claiming", nft.treasuryClaimPct / 100, "% of treasury");

        // Get balances before burn
        const userBalanceBefore = await provider.connection.getBalance(user.publicKey);
        const treasuryBalanceBefore = await provider.connection.getBalance(treasuryPda);
        console.log("User SOL before:", userBalanceBefore / LAMPORTS_PER_SOL);
        console.log("Treasury SOL before:", treasuryBalanceBefore / LAMPORTS_PER_SOL);

        // Calculate expected claim
        const expectedClaim = Math.floor((treasuryBalanceBefore * nft.treasuryClaimPct) / 10000);
        console.log("Expected claim:", expectedClaim / LAMPORTS_PER_SOL, "SOL");

        // Burn NFT for treasury claim
        await program.methods
            .burnForTreasury()
            .accounts({
                state: statePda,
                starNft: starNftPda,
                treasury: treasuryPda,
                user: user.publicKey,
                systemProgram: anchor.web3.SystemProgram.programId,
            })
            .rpc();

        // Verify treasury decreased
        const treasuryBalanceAfter = await provider.connection.getBalance(treasuryPda);
        expect(treasuryBalanceAfter).to.be.lessThan(treasuryBalanceBefore);
        console.log("Treasury SOL after:", treasuryBalanceAfter / LAMPORTS_PER_SOL);
        console.log("Treasury claimed:", (treasuryBalanceBefore - treasuryBalanceAfter) / LAMPORTS_PER_SOL, "SOL");

        // Verify NFT account is closed
        try {
            await program.account.starNft.fetch(starNftPda);
            expect.fail("NFT account should be closed");
        } catch (err: any) {
            expect(err.toString()).to.include("Account does not exist");
            console.log("NFT account correctly closed after burn!");
        }

        // Verify state updated
        const stateAfter = await program.account.starNftState.fetch(statePda);
        expect(stateAfter.totalNftsBurned.toNumber()).to.be.greaterThan(0);
        expect(stateAfter.totalTreasuryClaimed.toNumber()).to.be.greaterThan(0);
    });

    it("Cannot burn NFT owned by someone else", async () => {
        const user = provider.wallet;
        const attacker = Keypair.generate();

        // Airdrop to attacker
        await provider.connection.requestAirdrop(attacker.publicKey, LAMPORTS_PER_SOL);
        await new Promise(resolve => setTimeout(resolve, 1000));

        // Get user's NFT (the first one minted)
        const [starNftPda] = PublicKey.findProgramAddressSync(
            [
                Buffer.from("star_nft"),
                user.publicKey.toBuffer(),
                new anchor.BN(0).toArrayLike(Buffer, "le", 8), // First NFT
            ],
            program.programId
        );

        // Try to burn as attacker
        try {
            await program.methods
                .burnForTreasury()
                .accounts({
                    state: statePda,
                    starNft: starNftPda,
                    treasury: treasuryPda,
                    user: attacker.publicKey,
                    systemProgram: anchor.web3.SystemProgram.programId,
                })
                .signers([attacker])
                .rpc();

            expect.fail("Should have failed - not NFT owner");
        } catch (err: any) {
            // Either NotNftOwner or constraint violation
            expect(err.toString()).to.match(/NotNftOwner|Constraint/i);
            console.log("Correctly rejected burn attempt by non-owner!");
        }
    });

    it("Mints multiple NFTs with different rarities", async () => {
        const user = provider.wallet;
        const userStardustAccount = await getAssociatedTokenAddress(
            stardustMint,
            user.publicKey
        );

        // Mint some more stardust
        await mintTo(
            provider.connection,
            stardustMintAuthority,
            stardustMint,
            userStardustAccount,
            stardustMintAuthority,
            STARDUST_COST.toNumber() * 10
        );

        const rarityCount = [0, 0, 0, 0, 0];
        const rarityNames = ["Common", "Uncommon", "Rare", "Epic", "Legendary"];

        // Mint 10 NFTs to see rarity distribution
        for (let i = 0; i < 10; i++) {
            const state = await program.account.starNftState.fetch(statePda);
            const nftIndex = state.totalNftsMinted;

            const [starNftPda] = PublicKey.findProgramAddressSync(
                [
                    Buffer.from("star_nft"),
                    user.publicKey.toBuffer(),
                    nftIndex.toArrayLike(Buffer, "le", 8),
                ],
                program.programId
            );

            await program.methods
                .mintStarNft()
                .accounts({
                    state: statePda,
                    starNft: starNftPda,
                    stardustMint: stardustMint,
                    userStardust: userStardustAccount,
                    user: user.publicKey,
                    tokenProgram: anchor.utils.token.TOKEN_PROGRAM_ID,
                    systemProgram: anchor.web3.SystemProgram.programId,
                })
                .rpc();

            const nft = await program.account.starNft.fetch(starNftPda);
            rarityCount[nft.rarity]++;
        }

        console.log("\nRarity distribution from 10 mints:");
        for (let i = 0; i < 5; i++) {
            console.log(`  ${rarityNames[i]}: ${rarityCount[i]}`);
        }

        const finalState = await program.account.starNftState.fetch(statePda);
        console.log("\nTotal NFTs minted:", finalState.totalNftsMinted.toNumber());
        console.log("Total NFTs burned:", finalState.totalNftsBurned.toNumber());
        console.log("Total treasury claimed:", finalState.totalTreasuryClaimed.toNumber() / LAMPORTS_PER_SOL, "SOL");
    });
});
