import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import {
    Keypair,
    PublicKey,
    Transaction,
    TransactionInstruction,
    Ed25519Program,
    SYSVAR_INSTRUCTIONS_PUBKEY,
} from "@solana/web3.js";
import {
    getAssociatedTokenAddress,
    createAssociatedTokenAccountInstruction,
    getAccount,
} from "@solana/spl-token";
import * as nacl from "tweetnacl";
import { expect } from "chai";

// Import the IDL type (generated by anchor build)
import { Stardust } from "../target/types/stardust";

describe("stardust", () => {
    const provider = anchor.AnchorProvider.env();
    anchor.setProvider(provider);

    const program = anchor.workspace.Stardust as Program<Stardust>;

    // Backend authority keypair (in production, this would be securely stored)
    const authority = Keypair.generate();

    // PDAs
    let statePda: PublicKey;
    let stateBump: number;
    let stardustMintPda: PublicKey;
    let stardustMintBump: number;

    before(async () => {
        // Derive PDAs
        [statePda, stateBump] = PublicKey.findProgramAddressSync(
            [Buffer.from("state")],
            program.programId
        );

        [stardustMintPda, stardustMintBump] = PublicKey.findProgramAddressSync(
            [Buffer.from("stardust_mint")],
            program.programId
        );
    });

    it("Initializes the protocol", async () => {
        await program.methods
            .initialize(authority.publicKey)
            .accounts({
                state: statePda,
                stardustMint: stardustMintPda,
                payer: provider.wallet.publicKey,
                systemProgram: anchor.web3.SystemProgram.programId,
                tokenProgram: anchor.utils.token.TOKEN_PROGRAM_ID,
                rent: anchor.web3.SYSVAR_RENT_PUBKEY,
            })
            .rpc();

        // Verify state
        const state = await program.account.protocolState.fetch(statePda);
        expect(state.authority.toBase58()).to.equal(authority.publicKey.toBase58());
        expect(state.stardustMint.toBase58()).to.equal(stardustMintPda.toBase58());

        console.log("Protocol initialized!");
        console.log("Authority:", authority.publicKey.toBase58());
        console.log("Stardust Mint:", stardustMintPda.toBase58());
    });

    it("Claims stardust with valid signature", async () => {
        const user = provider.wallet;
        const lifetimeEarned = new anchor.BN(1000_000_000_000); // 1000 stardust (with 9 decimals)

        // Create user's associated token account
        const userTokenAccount = await getAssociatedTokenAddress(
            stardustMintPda,
            user.publicKey
        );

        // Create ATA instruction if needed
        const ataIx = createAssociatedTokenAccountInstruction(
            user.publicKey,
            userTokenAccount,
            user.publicKey,
            stardustMintPda
        );

        // Construct message: [UserPubkey(32) | LifetimeEarned(8)]
        const message = Buffer.concat([
            user.publicKey.toBuffer(),
            lifetimeEarned.toArrayLike(Buffer, "le", 8),
        ]);

        // Sign message with authority
        const signature = nacl.sign.detached(message, authority.secretKey);

        // Create Ed25519 verification instruction
        const ed25519Ix = Ed25519Program.createInstructionWithPublicKey({
            publicKey: authority.publicKey.toBytes(),
            message: message,
            signature: signature,
        });

        // User claim PDA
        const [userClaimPda] = PublicKey.findProgramAddressSync(
            [Buffer.from("user_claim"), user.publicKey.toBuffer()],
            program.programId
        );

        // Build claim instruction
        const claimIx = await program.methods
            .claimStardust(lifetimeEarned)
            .accounts({
                user: user.publicKey,
                userClaim: userClaimPda,
                state: statePda,
                stardustMint: stardustMintPda,
                userTokenAccount: userTokenAccount,
                instructions: SYSVAR_INSTRUCTIONS_PUBKEY,
                systemProgram: anchor.web3.SystemProgram.programId,
                tokenProgram: anchor.utils.token.TOKEN_PROGRAM_ID,
            })
            .instruction();

        // Build transaction with Ed25519 verification FIRST
        const tx = new Transaction();
        tx.add(ataIx); // Create ATA
        tx.add(ed25519Ix); // Ed25519 verification (index 1)
        tx.add(claimIx); // Claim stardust (index 2)

        await provider.sendAndConfirm(tx);

        // Verify user received tokens
        const tokenAccountInfo = await getAccount(
            provider.connection,
            userTokenAccount
        );
        expect(Number(tokenAccountInfo.amount)).to.equal(
            lifetimeEarned.toNumber()
        );

        // Verify claim state updated
        const userClaim = await program.account.userClaim.fetch(userClaimPda);
        expect(userClaim.claimedAmount.toNumber()).to.equal(
            lifetimeEarned.toNumber()
        );

        console.log("Claimed", lifetimeEarned.toNumber() / 1e9, "stardust!");
    });

    it("Replay with same lifetime_earned yields zero (fails)", async () => {
        const user = provider.wallet;
        const lifetimeEarned = new anchor.BN(1000_000_000_000); // Same amount as before

        const userTokenAccount = await getAssociatedTokenAddress(
            stardustMintPda,
            user.publicKey
        );

        // Construct message
        const message = Buffer.concat([
            user.publicKey.toBuffer(),
            lifetimeEarned.toArrayLike(Buffer, "le", 8),
        ]);

        // Sign message
        const signature = nacl.sign.detached(message, authority.secretKey);
        const ed25519Ix = Ed25519Program.createInstructionWithPublicKey({
            publicKey: authority.publicKey.toBytes(),
            message: message,
            signature: signature,
        });

        const [userClaimPda] = PublicKey.findProgramAddressSync(
            [Buffer.from("user_claim"), user.publicKey.toBuffer()],
            program.programId
        );

        const claimIx = await program.methods
            .claimStardust(lifetimeEarned)
            .accounts({
                user: user.publicKey,
                userClaim: userClaimPda,
                state: statePda,
                stardustMint: stardustMintPda,
                userTokenAccount: userTokenAccount,
                instructions: SYSVAR_INSTRUCTIONS_PUBKEY,
                systemProgram: anchor.web3.SystemProgram.programId,
                tokenProgram: anchor.utils.token.TOKEN_PROGRAM_ID,
            })
            .instruction();

        const tx = new Transaction();
        tx.add(ed25519Ix);
        tx.add(claimIx);

        try {
            await provider.sendAndConfirm(tx);
            expect.fail("Should have failed with NothingToClaim");
        } catch (err: any) {
            expect(err.toString()).to.include("NothingToClaim");
            console.log("Correctly rejected replay attempt!");
        }
    });

    it("Claims additional stardust when lifetime increases", async () => {
        const user = provider.wallet;
        const newLifetimeEarned = new anchor.BN(2500_000_000_000); // 2500 stardust total

        const userTokenAccount = await getAssociatedTokenAddress(
            stardustMintPda,
            user.publicKey
        );

        // Construct message with new lifetime
        const message = Buffer.concat([
            user.publicKey.toBuffer(),
            newLifetimeEarned.toArrayLike(Buffer, "le", 8),
        ]);

        const signature = nacl.sign.detached(message, authority.secretKey);
        const ed25519Ix = Ed25519Program.createInstructionWithPublicKey({
            publicKey: authority.publicKey.toBytes(),
            message: message,
            signature: signature,
        });

        const [userClaimPda] = PublicKey.findProgramAddressSync(
            [Buffer.from("user_claim"), user.publicKey.toBuffer()],
            program.programId
        );

        const claimIx = await program.methods
            .claimStardust(newLifetimeEarned)
            .accounts({
                user: user.publicKey,
                userClaim: userClaimPda,
                state: statePda,
                stardustMint: stardustMintPda,
                userTokenAccount: userTokenAccount,
                instructions: SYSVAR_INSTRUCTIONS_PUBKEY,
                systemProgram: anchor.web3.SystemProgram.programId,
                tokenProgram: anchor.utils.token.TOKEN_PROGRAM_ID,
            })
            .instruction();

        const tx = new Transaction();
        tx.add(ed25519Ix);
        tx.add(claimIx);

        await provider.sendAndConfirm(tx);

        // Should now have 2500 total (1000 from before + 1500 new)
        const tokenAccountInfo = await getAccount(
            provider.connection,
            userTokenAccount
        );
        expect(Number(tokenAccountInfo.amount)).to.equal(
            newLifetimeEarned.toNumber()
        );

        console.log("Claimed additional 1500 stardust! Total:", newLifetimeEarned.toNumber() / 1e9);
    });

    it("Rejects claim with wrong authority signature", async () => {
        const user = provider.wallet;
        const lifetimeEarned = new anchor.BN(5000_000_000_000);
        const fakeAuthority = Keypair.generate();

        const userTokenAccount = await getAssociatedTokenAddress(
            stardustMintPda,
            user.publicKey
        );

        const message = Buffer.concat([
            user.publicKey.toBuffer(),
            lifetimeEarned.toArrayLike(Buffer, "le", 8),
        ]);

        // Sign with WRONG authority
        const signature = nacl.sign.detached(message, fakeAuthority.secretKey);
        const ed25519Ix = Ed25519Program.createInstructionWithPublicKey({
            publicKey: fakeAuthority.publicKey.toBytes(), // Wrong pubkey
            message: message,
            signature: signature,
        });

        const [userClaimPda] = PublicKey.findProgramAddressSync(
            [Buffer.from("user_claim"), user.publicKey.toBuffer()],
            program.programId
        );

        const claimIx = await program.methods
            .claimStardust(lifetimeEarned)
            .accounts({
                user: user.publicKey,
                userClaim: userClaimPda,
                state: statePda,
                stardustMint: stardustMintPda,
                userTokenAccount: userTokenAccount,
                instructions: SYSVAR_INSTRUCTIONS_PUBKEY,
                systemProgram: anchor.web3.SystemProgram.programId,
                tokenProgram: anchor.utils.token.TOKEN_PROGRAM_ID,
            })
            .instruction();

        const tx = new Transaction();
        tx.add(ed25519Ix);
        tx.add(claimIx);

        try {
            await provider.sendAndConfirm(tx);
            expect.fail("Should have failed with InvalidAuthority");
        } catch (err: any) {
            expect(err.toString()).to.include("InvalidAuthority");
            console.log("Correctly rejected wrong authority!");
        }
    });
});
